### ISSUE TITLE
FanDuel prevents more than 4 players from single team

### ISSUE THREAD

**Issue by BenBrostoff** [BenBrostoff/draft-kings-fun#72]

**Comment by sharkiteuthis** [comment]
is this fixed now?

**Comment by amoran** [comment]
@BenBrostoff I believe this issue is still happening.  Lineups are generated that have more than 4 players from the same team.  Fanduel does not allow that.  Was a fix in progress?

**Comment by BenBrostoff** [comment]
@amoran Can you post an example here? That will help me write a test case I can then work on passing.
